@baseUrl = http://localhost:3000
### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}

### ExemploDeRota

# @name ExemploDeRota
GET {{baseUrl}}/ex/

### ConceitosManualController Home

# @name ConceitosManualControllerHome
GET {{baseUrl}}/conceitos-manual

### ConceitosAutomaticoController Home

# @name ConceitosAutomaticoControllerHome
GET {{baseUrl}}/conceitos-automatico