@baseUrl = http://localhost:3000

# RECADOS
### Lista todos os recados
GET {{baseUrl}}/recados/
?limit=10
&offset=0
### Lista apenas um recado
GET {{baseUrl}}/recados/1/
### Cria um recado
POST {{baseUrl}}/recados/
Content-Type: application/json

 {
  "texto": "Novo Recado",
  "de": "Joana",
  "para": "João"
}

### Atualiza um recado
PATCH {{baseUrl}}/recados/2/
Content-Type: application/json

{
  "texto": "Novo Recado",
  "de": "Joana",
  "para": "João"
}

### Apaga um recado
DELETE {{baseUrl}}/recados/1/

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}

### ExemploDeRota

# @name ExemploDeRota
GET {{baseUrl}}/ex/
