@baseUrl = http://localhost:3000

# RECADOS
### Lista todos os recados
GET {{baseUrl}}/recados/
?limit=5
&offset=0
### Lista apenas um recado
GET {{baseUrl}}/recados/2/
### Cria um recado
POST {{baseUrl}}/recados/
Content-Type: application/json

 {
  "texto": "Novo Recado",
  "deId": 4,
  "paraID": 1
}

### Atualiza um recado
PATCH {{baseUrl}}/recados/2/
Content-Type: application/json

{
  "lido": true
}

### Apaga um recado
DELETE {{baseUrl}}/recados/9/

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}

### ExemploDeRota

# @name ExemploDeRota
GET {{baseUrl}}/ex/








# Pessoas
### Lista todos os Pessoas
GET {{baseUrl}}/pessoas/
?limit=10
&offset=0
### Lista apenas uma Pessoa
GET {{baseUrl}}/pessoas/2/
### Cria uma Pessoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json

 {
 "email": "juze@email.com",
 "password": "123456",
 "nome": "Juze"

}

### Apaga uma Pessoa
DELETE {{baseUrl}}/pessoas/3/

### Atualiza uma pessoa
PATCH {{baseUrl}}/pessoas/4/
Content-Type: application/json

{
  "password": "654321",
  "nome": "Juaum"
}







# AUTH


### Login
POST {{baseUrl}}/auth/
Content-Type: application/json

{
 "email": "juze@email.com",
 "password": "123456",
 "nome": "Juze"
}
